version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway
    ports:
      - "8080:8080"
    depends_on:
      - db
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
    - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareitprod

  db:
    image: postgres:13.7-alpine
    container_name: postgres_shareit
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - DB_NAME=shareitprod
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
